default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

 
production:
  <<: *default
  database: docker_example_production #CHANGE ME
